[tool.poetry]
name = "surrealdb"
version = "0.1.0"
description = "SurrealDB driver for Python"
# TODO: Add an author
authors = []
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
msgspec = {version = "^0.9.0", optional = true}
charset-normalizer = {version = "^2.1.1", optional = true}
aiodns = {version = "^3.0.0", optional = true}
Brotli = {version = "^1.0.9", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.8.0"
isort = "^5.10.1"

[tool.poetry.extras]
speed = [ "msgspec", "orjson", "charset-normalizer", "aiodns", "Brotli" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
